In [4]:
import pandas as pd
df = pd.read_csv('/content/sample_data/Salary_Data.csv')
df

    YearsExperience    Salary
0               1.1   39343.0
1               1.3   46205.0
2               1.5   37731.0
3               2.0   43525.0
4               2.2   39891.0
5               2.9   56642.0
6               3.0   60150.0
7               3.2   54445.0
8               3.2   64445.0
9               3.7   57189.0
10              3.9   63218.0
11              4.0   55794.0
12              4.0   56957.0
13              4.1   57081.0
14              4.5   61111.0
15              4.9   67938.0
16              5.1   66029.0
17              5.3   83088.0
18              5.9   81363.0
19              6.0   93940.0
20              6.8   91738.0
21              7.1   98273.0
22              7.9  101302.0
23              8.2  113812.0
24              8.7  109431.0
25              9.0  105582.0
26              9.5  116969.0
27              9.6  112635.0
28             10.3  122391.0
29             10.5  121872.0

In [11]:
# df.info()
# df.describe()
# df.shape
# df.columns
df.isna().sum()

YearsExperience    0
Salary             0
dtype: int64

In [13]:
df.duplicated().sum() # Is there any duplicate records/values available

0

In [17]:
X = df.drop(columns = ['Salary'])

In [20]:
y = df['Salary']
y

0      39343.0
1      46205.0
2      37731.0
3      43525.0
4      39891.0
5      56642.0
6      60150.0
7      54445.0
8      64445.0
9      57189.0
10     63218.0
11     55794.0
12     56957.0
13     57081.0
14     61111.0
15     67938.0
16     66029.0
17     83088.0
18     81363.0
19     93940.0
20     91738.0
21     98273.0
22    101302.0
23    113812.0
24    109431.0
25    105582.0
26    116969.0
27    112635.0
28    122391.0
29    121872.0
Name: Salary, dtype: float64

In [27]:
from sklearn.linear_model import LinearRegression
model = LinearRegression()
# model.fit(X,y)
# y_predict = model.predict(X)
# from sklearn.metrics import r2_score
# score = r2_score(y, y_predict)
# score

from sklearn.model_selection import train_test_split
X_train,X_test,y_train,y_test = train_test_split(X,y,test_size=0.3,)
model.fit(X_train, y_train)
prediction = model.predict(X_test)

from sklearn.metrics import r2_score
score = r2_score(y_test, prediction)
score

0.9719097548481547